allowed:
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - apache-2.0

reviewed:
  bundler:
    - pathname-common_prefix
  rubygem:
    - pathname-common_prefix
    - bundler

ignored:
  bundler:
    - bundler
